---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
#rmarkdown::render("dashboard.Rmd", output_format = "flexdashboard::flex_dashboard")
```

```{r}
data("instacart") 
data_insta = instacart |>
  drop_na() |>
  filter(
    department == "personal care" & aisle != "oral hygiene" & aisle != "soap" & aisle != "vitamins supplements" 
  )
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
data_insta |>
  mutate(aisle = fct_reorder(aisle, order_hour_of_day)) |> 
  plot_ly(
    x = ~aisle, y = ~order_hour_of_day, color = ~aisle, 
    type = "box", colors = "viridis"
  ) |>
  layout(
    title = "Personal Care Product Purchases: Distribution by Hour of Day",
    xaxis = list(title = "Personal Care Aisle"),
    yaxis = list(title = "Hour of Day")
  )
```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
data_insta |> 
  group_by(order_hour_of_day) |>
  mutate(mean_order_number = mean(order_number)) |>
  plot_ly(
    x = ~order_hour_of_day, y = ~mean_order_number, color = ~order_hour_of_day, 
    type = "scatter", mode = "markers", alpha = 0.5
  )|>
  layout(
    title = "Mean Order Number by Hour of Day",
    xaxis = list(title = "Hour of Day"),
    yaxis = list(title = "Mean Order number")
  )
```

### Chart C

```{r}
data_insta |> 
  count(aisle) |> 
  mutate(aisle = fct_reorder(aisle, n)) |> 
  plot_ly(
    x = ~aisle, y = ~n, 
    type = "bar") |>
  layout(
    title = "Count of Personal Care Products",
    xaxis = list(title = "Personal Care Products"),
    yaxis = list(title = "Count")
  )
```

